### ISSUE TITLE
Please allow decimal places to be configured

### ISSUE THREAD

**Issue by rrthomas** [troizet/just-shows-memory-usage#1]
Thanks for writing this extension! I installed it because I keep running out of memory and crashing my laptop, so this prevents me having to open a terminal and run `top` all the time.

I find the constant updating distracting, and I fixed it for me by changing it to output only whole numbers of gigabytes (i.e. changing the argument to `toFixed` to `0`). Could you possibly make this an option, please?

**Comment by troizet** [comment]
Sorry for the delay in replying. I will try to add as soon as possible the possibility to customize the number of decimal places and to customize the refresh time. It all depends on my free time.

**Comment by troizet** [comment]
Done.

**Comment by rrthomas** [comment]
Many thanks, working for me!
