### ISSUE TITLE
Installation instructions improvements

### ISSUE THREAD

**Issue by rrthomas** [troizet/just-shows-memory-usage#4]
`README.md` says:

> Please follow the instructions for installation: https://gjs.guide/extensions/development/creating.html#gnome-extensions-tool

But I cannot find any installation instructions there.

Instead, I used the help output of `gnome-extensions` to work out the following incantation:

```sh
gnome-extensions pack .
gnome-extensions install --force just_shows_memory_usage@troizet.github.com.shell-extension.zip
```

(`--force` is only required if the extension is already installed.)

Also, `README.md` does not mention `extensions.gnome.org`. If you could indicate your preference, I'd be happy to rewrite the instructions suitably.

**Comment by troizet** [comment]
> If you could indicate your preference, I'd be happy to rewrite the instructions suitably.

 That would be good, thank you!

**Comment by rrthomas** [comment]
Sorry, I wasn't clear. I meant by "indicate your preference" for you to say how you would like the instructions changed. I can list the commands I used, or I can point to a (different?) page. I can mention `extensions.gnome.org` or I can not mention it (but I guess that's a no-brainer!).

**Comment by troizet** [comment]
Updated `README.md`.

**Comment by rrthomas** [comment]
Many thanks for this!
